version: '3.8'
services:
  animals:
    container_name: msanimals
    build: ./backend/animals-ms
    volumes:
      - ./backend/animals-ms:/usr/src/app
    networks:
      - mssafari
    ports:
      - "3013:3013"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  events:
    container_name: msevents
    build: ./backend/events-ms
    volumes:
      - ./backend/events-ms:/usr/src/app
    networks:
      - mssafari
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  users:
    container_name: msusers
    build: ./backend/users-ms
    volumes:
      - ./backend/users-ms:/usr/src/app
    networks:
      - mssafari
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  models:
    container_name: msmodels
    build: ./backend/models-ms
    volumes:
      - ./backend/models-ms:/usr/src/app
    networks:
      - mssafari
    ports:
      - "3014:3014"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  apigateway:
    container_name: apigateway
    build: ./backend/api-gateway
    volumes:
      - ./backend/api-gateway/code:/usr/src/app
    networks:
      - mssafari
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  animaldetails:
    container_name: animal-details
    build: ./backend/animal-details
    volumes:
      - ./backend/animal-details:/usr/src/app
    networks:
      - mssafari
    ports:
      - "3018:3018"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  client:
    image: client
    restart: on-failure
    build:
      context: ./Hangout-Safari
      dockerfile: Dockerfile
    networks:
      - mssafari
    ports:
      - 3000:3000
    volumes:
      - ./Hangout-Safari:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
networks:
  mssafari:
    driver: bridge
